### PR TITLE
Add option to get_gyro() method to return turning rate in radians/s

### PR DESCRIPTION
**Pull request by blmorris**
instead of degrees/s

### CODE REVIEW

**Comment by turbinenreiter** [comment]
Merged and updated doc.

**Comment by blmorris** [comment]
Thanks! 
I also have an idea for a slightly less obvious addition. I need to negate the x-axis values for the accel and mag sensors and the y and z values for the gyros to get the correct results from the sensor fusion code I am using. (I don't know why this is, as your code returns results consistent with the orientation described in the MPU9150 datasheet.)
I would like to be able to pass an argument to get_gyro(), get_mag(), and get_accel() to select certain arguments to negate.
Example: get_gyro(neg='yz'), using a similar interface to the one to select a subset of sensor readings. This will let me streamline my code to stream data to the sensor fusion code; I imagine that there may be other situations where users may want to change the sign on specific axes. 
I think I know how to do it, I'll try to put the code together in a day or so.

**Comment by turbinenreiter** [comment]
Okay, if necessary.

Wouldn't this work from caller side? With [1,2,3] replaced by mpu.get_accel().
``python
>>> [a,b,c] = [1,2,3]
>>> [a,b,c] = [-a,-b,c]
>>> a
-1
>>> b
-2
>>> c
3
``

**Comment by blmorris** [comment]
Not strictly necessary, of course.
I was just hoping to be able to do something like the following in my code:
``` python
msg_data = bytes(array.array('f', get_gyro(neg='yz'))) + \
                    bytes(array.array('f', get_accel(neg='x'))) + \
                    bytes(array.array('f', get_mag(neg='x')))
```
Which would be a wonderfully compact way to create my data buffer with the hex representations of all 9 floating point measurements. However, I would still need an intermediate function to add my computed gyro bias compensation, and it probably isn't worth polluting your library with unnecessary features just to make this one example work.
I can still clean up my code using the idiom you suggest, so thanks.

**Pull request merged**
